apiVersion: v1
kind: Pod
metadata:
  name: fastapi-pod-configmap
spec:
  containers:
    - name: api
      image: localhost:5000/myfirstcontainer:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      envFrom:
        - configMapRef:
            name: my-config